// <auto-generated />
using System;
using ICPCLike.Db.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ICPCLike.Db.Migrations
{
    [DbContext(typeof(IcpcLikeContext))]
    [Migration("20250517220832_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ICPCLike.Db.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("organizations");
                });

            modelBuilder.Entity("ICPCLike.Db.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("IcpcId")
                        .HasColumnType("text")
                        .HasColumnName("icpc_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("Sex")
                        .HasColumnType("text")
                        .HasColumnName("sex");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("persons");
                });

            modelBuilder.Entity("ICPCLike.Db.Models.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PenaltyTime")
                        .HasColumnType("integer")
                        .HasColumnName("penalty_time");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<int>("SolvedTasks")
                        .HasColumnType("integer")
                        .HasColumnName("solved_tasks");

                    b.Property<int>("StageId")
                        .HasColumnType("integer")
                        .HasColumnName("stage_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.HasIndex("TeamId");

                    b.ToTable("results");
                });

            modelBuilder.Entity("ICPCLike.Db.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.ToTable("seasons");
                });

            modelBuilder.Entity("ICPCLike.Db.Models.Stage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("season_id");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("stages");
                });

            modelBuilder.Entity("ICPCLike.Db.Models.Substitution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NewContestantId")
                        .HasColumnType("integer")
                        .HasColumnName("new_contestant_id");

                    b.Property<int>("OldContestantId")
                        .HasColumnType("integer")
                        .HasColumnName("old_contestant_id");

                    b.Property<DateTime>("SubstitutionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("substitution_date");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("NewContestantId");

                    b.HasIndex("OldContestantId");

                    b.HasIndex("TeamId");

                    b.ToTable("substitutions");
                });

            modelBuilder.Entity("ICPCLike.Db.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Hidden")
                        .HasColumnType("boolean")
                        .HasColumnName("hidden");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer")
                        .HasColumnName("organization_id");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("teams");
                });

            modelBuilder.Entity("ICPCLike.Db.Models.TeamMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContestantId")
                        .HasColumnType("integer")
                        .HasColumnName("contestant_id");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("join_date");

                    b.Property<DateTime?>("LeaveDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("leave_date");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("ContestantId");

                    b.HasIndex("TeamId");

                    b.ToTable("team_members");
                });

            modelBuilder.Entity("ICPCLike.Db.Models.Result", b =>
                {
                    b.HasOne("ICPCLike.Db.Models.Stage", "Stage")
                        .WithMany("Results")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ICPCLike.Db.Models.Team", "Team")
                        .WithMany("Results")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ICPCLike.Db.Models.Stage", b =>
                {
                    b.HasOne("ICPCLike.Db.Models.Season", "Season")
                        .WithMany("Stages")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("ICPCLike.Db.Models.Substitution", b =>
                {
                    b.HasOne("ICPCLike.Db.Models.Person", "NewContestant")
                        .WithMany()
                        .HasForeignKey("NewContestantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ICPCLike.Db.Models.Person", "OldContestant")
                        .WithMany()
                        .HasForeignKey("OldContestantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ICPCLike.Db.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewContestant");

                    b.Navigation("OldContestant");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ICPCLike.Db.Models.Team", b =>
                {
                    b.HasOne("ICPCLike.Db.Models.Organization", "Organization")
                        .WithMany("Teams")
                        .HasForeignKey("OrganizationId");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("ICPCLike.Db.Models.TeamMember", b =>
                {
                    b.HasOne("ICPCLike.Db.Models.Person", "Contestant")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("ContestantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ICPCLike.Db.Models.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contestant");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("ICPCLike.Db.Models.Organization", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("ICPCLike.Db.Models.Person", b =>
                {
                    b.Navigation("TeamMemberships");
                });

            modelBuilder.Entity("ICPCLike.Db.Models.Season", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("ICPCLike.Db.Models.Stage", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("ICPCLike.Db.Models.Team", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
